[package]
name = "test-external-service"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
rapace.workspace = true
rapace-cell = { path = "../rust-legacy/rapace-cell" }
