[package]
name = "rapace-spec-peer"
version = "0.1.0"
edition = "2024"
description = "Rapace protocol spec peer (reference implementation)"
license = "MIT OR Apache-2.0"
publish = false

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[[bin]]
name = "rapace-spec-peer"
path = "src/main.rs"

[dependencies]
rapace-protocol.workspace = true
facet.workspace = true
facet-json.workspace = true
facet-postcard.workspace = true
clap = { version = "4", features = ["derive"] }
inventory = "0.3"
rapace-spec-peer-macros = { path = "../spec-peer-macros" }
tokio = { version = "1", features = ["full"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
